name: Deploy ELA Navigator

concurrency:
  group: deploy-production
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Ejecutar despliegue
        run: /home/adminpaco/elanavigator-guide/deploy.sh
